### ISSUE TITLE
2 error message

### ISSUE THREAD

**Issue by pncorpuz** [INTROSETERM2/SourceCodes#2]
pag minali ko input dun sa Price dalawang error message lumalabas
example:
Customer: Paulo Price: asd Staff: Edward

ERROR MESSAGE:
1.Please input numbers only on the price
2.Please fill in all the data

@Calvin-Glein  @ChesterGaw  @PatriciaLim

**Comment by ChesterGaw** [comment]
@Calvin-Glein may gawa niyan hahaha inayos na yata niya yan ah ata?
